name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check code formatting
      run: npm run format:check --if-present
    
    - name: Run ESLint
      run: npm run lint --if-present
    
    - name: Check TypeScript types
      run: npm run type-check --if-present

  dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check for outdated dependencies
      run: npm outdated
    
    - name: Check for security vulnerabilities
      run: npm audit
    
    - name: Create Dependabot PR
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pullRequests } = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            head: 'dependabot/npm_and_yarn'
          });
          
          if (pullRequests.length === 0) {
            console.log('No Dependabot PRs found. Consider enabling Dependabot for automatic dependency updates.');
          } else {
            console.log(`Found ${pullRequests.length} Dependabot PR(s):`);
            pullRequests.forEach(pr => {
              console.log(`- #${pr.number}: ${pr.title}`);
            });
          } 